### ISSUE TITLE
Put together a shared Google calendar

### ISSUE THREAD

**Issue by jhibbets** [Open-NC/leadership-tasks#1]
This is for Jill

**Comment by jhibbets** [comment]
I wonder if setting up a Google Group for all NC Brigade leaders and members would make this easier?

**Comment by ejaxon** [comment]
Setting up a Google Group makes sense to me. I'm not so sure it makes sense to have the group target all leaders *and* members, though. My inclination is to focus the Google Group on leadership (perhaps we can use the spreadsheet @marshallj set up for Slack for this as well). Since the goal of the Open NC is to support the brigades, adding an all-members communication channel has the potential to detract from brigade communications. And we have Github, Slack, and even additional Google Groups (as we set up for Are We Represented?) that can serve as collaboration channels.

**Comment by ejaxon** [comment]
BTW not entirely sure how this relates to the calendar, though.

**Comment by jhibbets** [comment]
We did this for NC Open Pass. Instead of adding all 20+ individual planners to the shared calendar, we were able to add the google groups, which extends the invite to all members. At least, I think that's how it worked.

**Comment by jhibbets** [comment]
Google Group is at: https://groups.google.com/forum/#!forum/open-nc

**Comment by jhibbets** [comment]
Shared calendar is set-up: https://calendar.google.com/calendar?cid=ZnNkMmtqM2Jqb2tybmV2bmJtdWN2OGFhcTRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ
